config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/show'

  resources :users, only: %i[index show] do
    member do
      get :favorite_user_index
      get :show_follower
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    resources :unlikes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable

  validates :username, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 500 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :unlikes, dependent: :destroy
  has_many :unliked_posts, through: :unlikes, source: :post
  attachment :avatar

  def posts
    Post.where(user_id: id)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'ゲスト'
      user.confirmed_at = Time.now
    end
  end

  def already_favorited?(post)
    favorites.exists?(post_id: post.id)
  end

  def already_unliked?(post)
    unlikes&.exists?(post_id: post.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    unfollow = following_relationships.find_by(following_id: other_user.id)
    unfollow.destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  def check_guest
    redirect_to root_path, alert: 'ゲストユーザーは削除できません。' if resource.email == 'guest@example.com'
  end

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to pages_show_path, notice: 'ゲストユーザーとしてログインしました。'
  rescue ActiveRecord::RecordInvalid => e
    pp e.record&.errors
    redirect_to root_path, alert: 'エラーが発生しました。'
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(15).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def favorite_user_index
    @post = Post.find_by(params[:id])
    #一旦リファクタしたけどなんかバグってそう
    likes = @post.favorites.pluck(:user_id)
    @users = User.find(likes)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div class="follow-user">
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>
</div>

app/views/users/_nav.html.erb
<div class="user-nav col-md-12">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item nav-link-user">
     <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">投稿一覧</a>
    </li>
    <li class="nav-item nav-link-user">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">いいね一覧</a>
     </li>
     <li class="nav-item nav-link-user">
       <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><%= @user.followings.count %>フォロー</a>
     </li>
     <li class="nav-item nav-link-user">
       <a class="nav-link" id="follower-tab" data-toggle="tab" href="#follower" role="tab" aria-controls="follower" aria-selected="false"><%= @user.followers.count %>フォロワー</a>
     </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <% @user.posts.each do |post| %>
        <%= link_to post do %>
        <div class="post-item post-list">
          <% if post.user.avatar_id.present? %>
            <%= image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
          <% end %>
          <div class="post-body">
            <div class="post-title">
              <%= post.title %>
            </div>
        <% end %>
        <div class="post-menu">
          <%= link_to post.user.username, user_path(post.user.id), class:'post-user' %>
          <%= post.created_at.strftime("%Y年%m月%d日") %>
          <% if current_user.already_favorited?(post) %>
            <span class="fas fa-thumbs-up like-btn-unlike"></span>
          <% else %>
            <span class="far fa-thumbs-up like-btn"></span>
          <% end %>
          <%= post.favorites.count %>
          <span class="far fa-comment comment-btn"></span>
          <%= post.comments.count %>
          <div class="post-tag">
            <%= render 'posts/tag_list', tag_list: post.tag_list %>
          </div>
         </div>
        </div>
      </div>
      <% end %>
      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab"><% @user.favorites.each do |favorite| %>
        <% post = Post.find_by(id: favorite.post_id) %>
        <%= link_to post do %>
        <div class="post-item post-list">
          <% if post.user.avatar_id.present? %>
            <%= image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
          <% end %>
          <div class="post-body">
            <div class="post-title">
              <%= post.title %>
            </div>
            <% end %>
            <div class="post-menu">
              <%= link_to post.user.username, user_path(post.user.id), class:'post-user' %>
              <%= post.created_at.strftime("%Y年%m月%d日") %>
              <% if current_user.already_favorited?(post) %>
                <span class="fas fa-thumbs-up like-btn-unlike"></span>
              <% else %>
                <span class="far fa-thumbs-up like-btn"></span>
              <% end %>
                <%= post.favorites.count %>
              <span class="far fa-comment comment-btn"></span>
              <%= post.comments.count %>
              <div class="post-tag">
                <%= render 'posts/tag_list', tag_list: post.tag_list %>
              </div>
            </div>
            </div>
           </div>
        <% end %>
       </div>
       <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
         <% @user.followings.each do |user| %>
           <div class="user-item user-list">
             <% if user.avatar_id.present? %>
               <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
             <% else %>
               <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
             <% end %>
              <div class="user-menu">
                <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
                <p class="user-profile"><%= user.profile %></p>
              </div>
             </div>
          <% end %>
         </div>
         <div class="tab-pane fade" id="follower" role="tabpanel" aria-labelledby="follower-tab">
           <% @user.followers.each do |user| %>
           <div class="user-item user-list">
             <% if user.avatar_id.present? %>
               <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
             <% else %>
               <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
             <% end %>
             <div class="user-menu">
               <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
               <p class="user-profile"><%= user.profile %></p>
              </div>
            </div>
           <% end %>
          </div>
       </div>
    </div>
 </div>

app/views/users/_post_user.html.erb
<% @user.posts.each do |post| %>
  <%= link_to post do %>
    <div class="col-md-4">
      <ul>
        <li>タイトル：<%= post.title %></li>
        <li>投稿日：<%= post.created_at.strftime("%Y年%m月%d日") %></li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/favorite_user_index.html.erb
<div class="users-index">
  <div class="container">
    <div class="user-item-box">
      <% @users.each do |user| %>
        <div class="user-item user-list">
          <% if user.avatar_id.present? %>
            <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
          <% end %>
          <div class="user-menu">
             <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
             <p class="user-profile"><%= user.profile %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-index">
  <div class="container">
    <div class="user-item-box">
      <% @users.each do |user| %>
        <div class="user-item user-list">
          <% if user.avatar_id.present? %>
            <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
          <% end %>
          <div class="user-menu">
             <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
             <p class="user-profile"><%= user.profile %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="posts-index">
  <div class="container">
    <div class="post-item-box">
      <% if @user.avatar_id.present? %>
      <div class="user-photo">
        <%= image_tag attachment_url(@user, :avatar, :fill, 200, 200, format: "jpg"), class: 'user-image' %>
     </div>
     <% else %>
     <div class="user-photo">
        <%= image_tag('/images/default.jpeg', size: '200x200', class: 'user-image') %>
     </div>
     <% end %>
     <div class="username-show">
      <h1><%= @user.username %></h1>
     </div>
     <div class="username-show">
       <%= link_to "フォロー中のユーザ一覧", show_follower_user_path(@user.id) %>
     </div>

     <%= render 'follow_form' %>

     <div class="profile-show">
       <%= @user.profile %>
     </div>
     <%= render 'nav' %>
    </div>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="users-index">
  <div class="container">
    <div class="user-item-box">
      <% @user.followings.each do |user| %>
        <div class="user-item user-list">
            <% if user.avatar_id.present? %>
            <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
            <% else %>
            <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
            <% end %>
          <div class="user-menu">
            <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
            <p class="user-profile"><%= user.profile %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>