config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/show'

  resources :users, only: %i[index show] do
    member do
      get :favorite_user_index
      get :show_follower
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    resources :unlikes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
end

app/views/pages/_nav.html.erb
 <div class="user-nav col-md-12">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item nav-link-user">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">投稿一覧</a>
        </li>
        <li class="nav-item nav-link-user">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">いいね一覧</a>
        </li>
        <li class="nav-item nav-link-user">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><%= current_user.followings.count %>フォロー</a>
        </li>
        <li class="nav-item nav-link-user">
          <a class="nav-link" id="follower-tab" data-toggle="tab" href="#follower" role="tab" aria-controls="follower" aria-selected="false"><%= current_user.followers.count %>フォロワー</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <% current_user.posts.each do |post| %>
            <%= link_to post do %>
              <div class="post-item post-list">
                <% if post.user.avatar_id.present? %>
                  <%= image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
                <% else %>
                  <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
                <% end %>
                <div class="post-body">
                  <div class="post-title">
                    <%= post.title %>
                  </div>
            <% end %>
            <div class="post-menu">
              <%= link_to post.user.username, user_path(post.user.id), class:'post-user' %>
              <%= post.created_at.strftime("%Y年%m月%d日") %>
              <% if current_user.already_favorited?(post) %>
                <span class="fas fa-thumbs-up like-btn-unlike"></span>
              <% else %>
                <span class="far fa-thumbs-up like-btn"></span>
              <% end %>
              <%= post.favorites.count %>
              <span class="far fa-comment comment-btn"></span>
              <%= post.comments.count %>
              <div class="post-tag">
              <%= render 'posts/tag_list', tag_list: post.tag_list %>
             </div>
         </div>
       </div>
     </div>
         <% end %>
</div>
<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
  <% current_user.favorites.each do |favorite| %>
  <% post = Post.find_by(id: favorite.post_id) %>
      <%= link_to post do %>
      <div class="post-item post-list">
        <% if post.user.avatar_id.present? %>
        <%= image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
        <% else %>
        <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
        <% end %>
       <div class="post-body">
         <div class="post-title">
           <%= post.title %>
         </div>
         <% end %>
         <div class="post-menu">
           <%= link_to post.user.username, user_path(post.user.id), class:'post-user' %>
           <%= post.created_at.strftime("%Y年%m月%d日") %>
           <% if current_user.already_favorited?(post) %>
           <span class="fas fa-thumbs-up like-btn-unlike"></span>
           <% else %>
           <span class="far fa-thumbs-up like-btn"></span>
           <% end %>
           <%= post.favorites.count %>
           <span class="far fa-comment comment-btn"></span>
           <%= post.comments.count %>
           <div class="post-tag">
           <%= render 'posts/tag_list', tag_list: post.tag_list %>
           </div>
         </div>
        </div>
      </div>
        <% end %>
</div>
<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
  <% current_user.followings.each do |user| %>
        <div class="user-item user-list">
          <% if user.avatar_id.present? %>
            <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
          <% end %>
          <div class="user-menu">
             <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
             <p class="user-profile"><%= user.profile %></p>
          </div>
        </div>
      <% end %>
  </div>
   <div class="tab-pane fade" id="follower" role="tabpanel" aria-labelledby="follower-tab">
   <% current_user.followers.each do |user| %>
        <div class="user-item user-list">
          <% if user.avatar_id.present? %>
            <%= image_tag attachment_url(user, :avatar, :fill, 70, 70, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '70x70', class: 'user-img') %>
          <% end %>
          <div class="user-menu">
             <p><%= link_to user.username, user_path(user.id), class:'user-name' %></p>
             <p class="user-profile"><%= user.profile %></p>
          </div>
        </div>
      <% end %>
    </div>
   </div>
  </div>
 </div>

app/views/pages/home.html.erb
<% provide(:title, "ホーム") %>
<div class="top-container">
  <h1>クラコピ</h1>
  <p>ネーミングとキャッチコピーの募集と提案ができるサービス</p>
  <div class="button-link">
    <%= link_to '新規登録', new_user_registration_path, class:"btn btn-primary" %>
  </div>
  <div class="btn-link">
    <%= link_to 'かんたんログイン', users_guest_sign_in_path, class:"btn btn-warning", method: :post %>
  </div>
</div>

<div class="jumbotron" id="about">
  <div class="container">
    <h1 class="display-5 primary">クラコピとは</h1>
    <p class="lead"></p>
    <hr class="my-4">
    <div class="button-jumbotron">
      <p>クラコピはあらゆるモノのネーミングやキャッチコピーの募集と提案ができるサービスです。</p>
      <h2>このようなお悩みを解決します<i class="far fa-lightbulb"></i></h2>
    </div>
    <ul class="jumbotron-list">
      <li><i class="fas fa-check"></i>商品の成約率を上げたい</li>
      <li><i class="fas fa-check"></i>人の目にとまる広告を出したい</li>
      <li><i class="fas fa-check"></i>Webサービスの名前を決めたい</li>
      <li><i class="fas fa-check"></i>新しく立ち上げる会社名が決まらない</li>
      <li><i class="fas fa-check"></i>サイトのファーストビューを改善したい</li>
      <li><i class="fas fa-check"></i>YouTubeでバズりそうなタイトル案が欲しい</li>
    </ul>
    <p class="jumbotron-p">上記は一例です。様々なネーミング、キャッチコピーを決める際にご活用できますのでぜひ一度ご活用ください。</p>
    <div class="btn-jumbotron">
      <%= link_to 'さっそく使ってみる', new_user_registration_path, class:"btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="posts-index">
  <div class="container">
    <div class="post-item-box">
      <% if current_user.avatar_id.present? %>
        <div class="user-photo">
          <%= image_tag attachment_url(current_user, :avatar, :fill, 200, 200, format: "jpg"), class: 'user-image' %>
        </div>
      <% else %>
        <div class="user-photo">
          <%= image_tag('/images/default.jpeg', size: '200x200', class: 'user-image') %>
        </div>
      <% end %>
      <div class="username-show">
        <h1><%= current_user.username %></h1>
        <%= link_to 'ユーザー情報編集', edit_user_registration_path, class: "btn btn-info btn-md" %>
      </div>
      <div class="profile-show">
        <%= current_user.profile %>
      </div>
      <%= render 'nav' %>
     </div>
   </div>
</div>