config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/show'

  resources :users, only: %i[index show] do
    member do
      get :favorite_user_index
      get :show_follower
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    resources :unlikes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 1000 }
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :unlikes, dependent: :destroy
  has_many :unliked_users, through: :unlikes, source: :user
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[show create]
  before_action :find_post, only: %i[show edit update destroy]
  before_action :set_favorite, only: %i[index show]
  before_action :validate_user, only: %i[edit update destroy]

  PER = 10

  def index
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(1000).pluck(:post_id))
    @posts = Post.page(params[:page]).per(PER).order(created_at: :desc)
  end

  def show
    @unlike = Unlike.new
    # 未実装のため一旦コメントアウト
    # @bookmark = Bookmark.new
    @user = User.find_by(id: @post.user_id)
    @comments = @post.comments.all
    @comment = @post.comments.build(user_id: current_user.id) if current_user
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice: '投稿しました'
    elsif @post.title.empty?
      redirect_to new_post_path, alert: 'タイトルを入力してください'
    else
      flash[:alert] = 'タイトルは50字以内、詳細は1000字以内で入力してください'
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: '投稿内容を変更しました'
    elsif @post.title.empty?
      redirect_to edit_post_path, alert: 'タイトルを入力してください'
    else
      render :edit, alert: '投稿内容を変更できませんでした'
    end
  end

  def destroy
    @post.destroy ? flash[:notice] = '投稿を削除しました' : flash[:alerts] = '投稿を削除できませんでした'
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def set_favorite
    @favorite = Favorite.new
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :content, :tag_list)
  end

  def validate_user
    redirect_to posts_path, alert: '投稿者以外はこの操作はできません' if @post.user != current_user
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="comment-list">
  <h3>提案リスト<i class="far fa-comment" style="padding: 0 2px 0 5px;"></i><%= @post.comments.count %></h3>
  <% @comments.each do |comment| %>
    <% if comment.user.avatar_id.present? %>
      <%= image_tag attachment_url(comment.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
    <% else %>
      <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
    <% end %>
      <%= link_to comment.user.username, user_path(comment.user.id) %>
      <% if comment.user_id == current_user.id %>
        <div class="comment-btn">
          <%= link_to '削除', post_comment_path(comment.post_id, comment.id), method: :delete, data: { confirm: "提案文を削除しますか？この操作は取り消せません。"}, class: "btn btn-danger btn-md" %>
        </div>
      <% end %>
      <hr style="margin-top: 4px;">
        <div class="comment-content">
          <%= simple_format comment.content %>
        </div>
        <div class="comment-time">
          <%= comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
        </div>
        <hr color="black">
   <% end %>
</div>

app/views/posts/_comment_form.html.erb
<% if @post.user_id != current_user.id %>
  <%= form_for [@post, @comment] do |f| %>
    <div class="form-group">
      <%= f.label :提案文作成 %>
      <%= f.text_area :content, rows: 6, autofocus: true, autocomplete: 'email', class: 'form-control' %>
    </div>
    <br>
    <div class="form-group">
      <%= f.submit '提案する', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for post, local: true do |f| %>

  <div class="form-group">
    <%= f.label :title, "タイトル（50字以内）" %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title, "依頼の詳細（1000字以内）" %>
    <%= f.text_area :body, rows: 8, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, "タグ（カンマ区切り）" %>
    <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control" %>
  </div>

  <div class="form-group">
    <i class="fas fa-camera"></i><%= f.label :title, "画像", class: "post-image-title" %><br>
    <%= f.attachment_field :image %>
    <img id="preview" style="width:25%;">
    <script>
      $('#post_image').on('change', function (e) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $("#preview").attr('src', e.target.result);
        }
        reader.readAsDataURL(e.target.files[0]);
      });
    </script>
  </div>

  <%= f.submit '投稿する', class: "btn btn-primary btn-block" %>
<% end %>

app/views/posts/_like.html.erb
<% if current_user.already_favorited?(@post) %>
    <%= link_to post_favorite_path(@post), method: :delete do %>
    <span class="fas fa-thumbs-up like-btn-unlike"></span>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(@post), method: :post do %><span class="far fa-thumbs-up like-btn"></span>
    <% end %>
  <% end %>
  <%= @post.favorites.count %>

app/views/posts/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-primary"><%= tag %></span>
<% end %>

app/views/posts/_unlike.html.erb
<% if current_user.already_unliked?(@post) %>
    <%= link_to post_unlike_path(@post), method: :delete do %>
    <span class="fas fa-thumbs-down like-btn-unlike"></span>
    <% end %>
  <% else %>
    <%= link_to post_unlikes_path(@post), method: :post do %><span class="far fa-thumbs-down like-btn"></span>
    <% end %>
  <% end %>
  <%= @post.unlikes.count %>

app/views/posts/edit.html.erb
<div class="posts-index">
  <div class="container">
    <div class="post-item-box">
      <div class="col-md-12">
        <h1><i class="far fa-edit"></i>投稿の編集</h1>
        <div class="new-post">
          <%= form_for @post do |f|%>
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :title, "本文" %>
            <%= f.text_area :body, rows: 8, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :tag_list, "タグ（カンマ区切り）" %>
            <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control" %>
          </div>
          <div class="form-group">
            <i class="fas fa-camera"></i><%= f.label :title, "画像の挿入・変更", class: "post-image-title" %><br>
            <%= f.attachment_field :image, class: "post-image" %>
          </div>
          <%= f.submit '投稿内容を変更する', class: "btn btn-info btn-block" %>
          <% end %>
        </div>
     </div>
   </div>
</div>

app/views/posts/index.html.erb
<div class="posts-index">
 <div class="container">
  <div class="post-item-box">
      <% @posts.each do |post| %>
      <%= link_to post do %>
      <div class="post-item post-list">
        <% if post.user.avatar_id.present? %>
        <%= image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
        <% else %>
        <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
        <% end %>
       <div class="post-body">
         <div class="post-title">
           <%= post.title %>
         </div>
         <% end %>
         <div class="post-menu">
           <%= link_to post.user.username, user_path(post.user.id), class:'post-user' %>
           <%= post.created_at.strftime("%Y年%m月%d日") %>
           <% if current_user.already_favorited?(post) %>
           <%= link_to post_favorite_path(post, post.id), method: :delete do %>
            <span class="fas fa-thumbs-up like-btn-unlike"></span>
            <% end %>
           <% else %>
             <%= link_to post_favorites_path(post, post.id), method: :post do %>
               <span class="far fa-thumbs-up like-btn"></span>
             <% end %>
           <% end %>
           <%= post.favorites.count %>
            <span class="far fa-comment comment-btn"></span>
           <%= post.comments.count %>
           <div class="post-tag">
           <%= render 'posts/tag_list', tag_list: post.tag_list %>
           </div>
         </div>
        </div>
      </div>
    <% end %>
  <%= paginate @posts %>
  </div>
 </div>
</div>

app/views/posts/new.html.erb
<div class="posts-index">
  <div class="container">
    <div class="post-item-box">
      <div class="col-md-12">
        <h1><i class="fas fa-edit"></i>投稿文作成</h1>
        <div class="new-post">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="posts-index">
  <div class="container">
    <div class="post-item-box">
      <div class="col-md-12">
        <div class="post-show-user">
          <% if @post.user.avatar_id.present? %>
            <%= image_tag attachment_url(@user, :avatar, :fill, 50, 50, format: "jpg"), class: 'user-img' %>
          <% else %>
            <%= image_tag('/images/default.jpeg', size: '50x50', class: 'user-img') %>
          <% end %>
          <div class="post-username">
            <%= link_to @user.username, user_path(@user.id) %>
            <div class="post-time">
              <%= @post.created_at.strftime("%Y年%m月%d日") %>
            </div>
            <%= render 'posts/like' %>
            <%= render 'posts/unlike' %>
            <div class="post-like-user">
              <%= link_to "いいねしたユーザー", favorite_user_index_user_path %>
            </div>
          </div>

        </div>
        <div class="post-show-title">
        <h2><%= @post.title %></h2>
        </div>
        <h3>案件の詳細</h3>
        <% if @post.image_id.present? %>
        <div class="post-img">
          <%= image_tag attachment_url(@post, :image, :fill, 350, 250, format: "jpg"), class: 'post-photo' %>
          </div>
        <% end %>
        <div class="post-body">
        <p><%= simple_format @post.body %></p>
        </div>
        <% if @post.user_id == current_user.id %>
        <div class="post-change">
          <%= link_to '案件を編集', edit_post_path(@post), class: "btn btn-info btn-md" %>
          <%= link_to '案件を削除', post_path(@post.id), method: :delete, data: { confirm: "投稿を削除しますか？この操作は取り消せません。"}, class: "btn btn-danger btn-md" %>
        <% end %>
        </div>
          <div class="comment-form">
            <%= render 'posts/comment' %>
            <%= render 'posts/comment_form' %>
          </div>
      </div>
    </div>
  </div>
</div>