config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/show'

  resources :users, only: %i[index show] do
    member do
      get :favorite_user_index
      get :show_follower
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
    resources :unlikes, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_flash_messages.html.erb
<p class="notice alert-success"><%= notice %></p>
<p class="alert-danger"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer>
  <address>Copyright(C)2019 K.HATA,Allright Reserved.</address>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md sticky-top" style="color: #white; background-color: #35477d;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/images/logo3.jpg"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item"><strong><%= link_to current_user.username, pages_show_path, class:"nav-link" %></strong></li>
          <li class="nav-item"><%= link_to  posts_path, class:"nav-link" do %><i class="far fa-newspaper"></i>案件一覧</li><% end %>
          <li class="nav-item"><%= link_to  new_post_path, class:"nav-link" do %><i class="fas fa-paper-plane"></i>投稿する</li><% end %>
          <li class="nav-item"><%= link_to  users_path, class:"nav-link" do %><i class="fas fa-users"></i>ユーザー一覧</li><% end %>
          <li class="nav-item"><%= link_to destroy_user_session_path, class:"nav-link", method: :delete do   %><i class="fas fa-sign-out-alt"></i>ログアウト</li><% end %>
        <% else %>
          <li class="nav-item"><%= link_to new_user_registration_path, class:"nav-link" do %><i class="fas fa-user-plus"></i>新規登録</li><% end %>
          <li class="nav-item"><button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><%= link_to new_user_session_path do %><i class="fas fa-sign-in-alt"></i>ログイン</button></li><% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>

     <%= render 'layouts/rails_default' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/ac8dfce5e3.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>